"""add parcel_image_url and delivery_code to parcel_orders

Revision ID: 24c182977ce2
Revises: e2f5a8b9c1d2
Create Date: 2026-02-14 18:29:11.824732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24c182977ce2'
down_revision = 'e2f5a8b9c1d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parcel_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parcel_image_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('delivery_code', sa.String(length=10), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('parcel_orders', schema=None) as batch_op:
        batch_op.drop_column('delivery_code')
        batch_op.drop_column('parcel_image_url')

    # ### end Alembic commands ###
